feat: Adding additional workflows
frmscoe/workflows pull request #15
Opened 2024-07-03 10:12 UTC by vorsterk

# SPDX-License-Identifier: Apache-2.0

## What did we change?

- Added additional workflows
   - conventional-commits
   - dco-check
   - gpg-verify
   - sync-workflows

## Why are we doing this?

For additional checks in the repositories.

## How was it tested?
- [ x] Locally
- [ ] Development Environment
- [ ] Not needed, changes very basic
- [ ] Husky successfully run
- [ ] Unit tests passing and Documentation done

2024-07-03 13:39 UTC, Justus-at-Tazama requested changes

2024-07-03 13:39 UTC, Justus-at-Tazama commented on .github/workflows/conventional-commits.yml
> +          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","BREAKING CHANGE"]'
Please refer to https://github.com/frmscoe/docs/blob/dev/Community/Tazama-Contribution-Guide.md#53-committing-your-changes - Tazama implements commit types based on the Angular specification, rather than the full Conventional Commits specification - specifically, `chore` is too generically "catch-all" and can overlap with some of the other commit types. We also include the `build` commit type to explicitly identify changes related to external dependencies. How is "BREAKING CHANGE" expected to be provided? Do we evaluate this as a commit "footer" as recommended in the specification? Typically the footer is a complement to one of the other statuses, and not a replacement. For example, the commit type will be `feat` and the feature is _also_ a breaking change. Without a footer, the commit type can also be used to indicate a breaking change by appending a `!` to the commit type, e.g. `feat!`.

2024-07-04 11:41 UTC, vorsterk commented on .github/workflows/conventional-commits.yml
> +          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","BREAKING CHANGE"]'
Ive updated those commits labels for you @Justus-at-Tazama . I will amend them on the release workflows im busy with now as well.

2024-07-04 13:20 UTC, Justus-at-Tazama approved these changes

2024-07-04 13:29 UTC, merged